#include "iautogen.h"


int main()
{
    autogenerator ag;
    ag.generate("/home/mark/workspace/projects/otus_course/architect/libs/spacebattle/ifaceproto",
                "/home/mark/workspace/projects/otus_course/architect/libs/spacebattle/include/autogenerated/");
    return 0;
}


